# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ankur.cc
email: ankurbohra123@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Thoughts on Entrepreneurship, Technology Startups, Product Management, Personal Development, AI, Machine Learning, Deeplearning, Maths and Data Science
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ankur.cc" # the base hostname & protocol for your site, e.g. http://example.com
#url: ""
twitter_username: ankurbohra
github_username:  silentvoice
github: [metadata]
# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed

minimal_mistakes_skin: "contrast" 
locale: "en-US"
name: "Ankur Bohra"
repository: "silentvoice/silentvoice.github.io"
permalink: /:categories/:title/
breadcrumbs: true
read_time: true

comments:
  provider: "disqus"
  disqus:
    shortname: "ankurbohra"
 
search: true
twitter:
  username: "ankurbohra"

social:
  type: Person
  name: Ankur Bohra # If the user or organization name differs from the site's name
  links:
    - "https://twitter.com/ankurbohra"
    - "https://www.linkedin.com/in/ankur-bohra"
    - "https://github.com/silentvoice"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-125054033-1"
    anonymize_ip: false # default    

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

author:
  name   : "Ankur Bohra"
 # avatar : "/assets/images/bio-photo.jpg"
  bio    : "My awesome biography constrained to a sentence or two goes here."
  email  : ankurbohra123@gmail.com
  uri    : "http://ankur.cc"
  home   : # null (default), "absolute or relative url to link to author home" 

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      comments: true



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
